language: node_js
node_js:
  - "14"
  - "16"
install:
  - npm i
  - npm i @justlep/nedb
  - npm i nedb@1.8.0
script:
  - npm run lint
  - npm run test:memory-nedb-original
  - npm run test:memory-nedb-justlep
  - npm run test:persistent-nedb-original
  - npm run test:persistent-nedb-justlep
